expect

# Wait enough (forever) until a long-time boot
set timeout -1

# Start VM
spawn fdisk [lindex $argv 0]

expect "Command (m for help):"
send "d\n"

expect "Partition number (1,2, default 2):"
send "2\n"

expect "Command (m for help):"
send "n\n"

expect "Select (default p):"
send "p\n"

expect "Partition number (2-4, default 2):"
send "2\n"

#this might be super sensitive to the image being used, adjust accordingly
expect "First sector"
send "532480\n"

expect "Last sector, +/-sectors or +/-size{K,M,G,T,P}"
send "\n"

expect "Do you want to remove the signature?"
send "N\n"

expect "Command (m for help):"
send "w\n"

interact
